name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.2.0

      - name: Compile LaTeX document
        run: latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: main.pdf
